<?php

use Illuminate\Database\Seeder;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->truncate();
        DB::table('languages')->insert([
                ['language_code' => 'en', 'language_name' => 'English'],
                ['language_code' => 'de', 'language_name' => 'German'],
                ['language_code' => 'fr', 'language_name' => 'French'],
                ['language_code' => 'nl', 'language_name' => 'Dutch'],
                ['language_code' => 'it', 'language_name' => 'Italian'],
                ['language_code' => 'es', 'language_name' => 'Spanish'],
                ['language_code' => 'pl', 'language_name' => 'Polish'],
                ['language_code' => 'ru', 'language_name' => 'Russian'],
                ['language_code' => 'ja', 'language_name' => 'Japanese'],
                ['language_code' => 'pt', 'language_name' => 'Portuguese'],
                ['language_code' => 'sv', 'language_name' => 'Swedish'],
                ['language_code' => 'zh', 'language_name' => 'Chinese'],
                ['language_code' => 'ca', 'language_name' => 'Catalan'],
                ['language_code' => 'uk', 'language_name' => 'Ukrainian'],
                ['language_code' => 'no', 'language_name' => 'Norwegian (Bokmål]'],
                ['language_code' => 'fi', 'language_name' => 'Finnish'],
                ['language_code' => 'vi', 'language_name' => 'Vietnamese'],
                ['language_code' => 'cs', 'language_name' => 'Czech'],
                ['language_code' => 'hu', 'language_name' => 'Hungarian'],
                ['language_code' => 'ko', 'language_name' => 'Korean'],
                ['language_code' => 'ind', 'language_name' => 'Indonesian'],
                ['language_code' => 'tr', 'language_name' => 'Turkish'],
                ['language_code' => 'ro', 'language_name' => 'Romanian'],
                ['language_code' => 'fa', 'language_name' => 'Persian'],
                ['language_code' => 'ar', 'language_name' => 'Arabic'],
                ['language_code' => 'da', 'language_name' => 'Danish'],
                ['language_code' => 'eo', 'language_name' => 'Esperanto'],
                ['language_code' => 'sr', 'language_name' => 'Serbian'],
                ['language_code' => 'lt', 'language_name' => 'Lithuanian'],
                ['language_code' => 'sk', 'language_name' => 'Slovak'],
                ['language_code' => 'ms', 'language_name' => 'Malay'],
                ['language_code' => 'he', 'language_name' => 'Hebrew'],
                ['language_code' => 'bg', 'language_name' => 'Bulgarian'],
                ['language_code' => 'sl', 'language_name' => 'Slovenian'],
                ['language_code' => 'vo', 'language_name' => 'Volapük'],
                ['language_code' => 'kk', 'language_name' => 'Kazakh'],
                ['language_code' => 'war', 'language_name' => 'Waray-Waray'],
                ['language_code' => 'eu', 'language_name' => 'Basque'],
                ['language_code' => 'hr', 'language_name' => 'Croatian'],
                ['language_code' => 'hi', 'language_name' => 'Hindi'],
                ['language_code' => 'et', 'language_name' => 'Estonian'],
                ['language_code' => 'az', 'language_name' => 'Azerbaijani'],
                ['language_code' => 'gl', 'language_name' => 'Galician'],
                ['language_code' => 'simple', 'language_name' => 'Simple English'],
                ['language_code' => 'nn', 'language_name' => 'Norwegian (Nynorsk]'],
                ['language_code' => 'th', 'language_name' => 'Thai'],
                ['language_code' => 'new', 'language_name' => 'Newar / Nepal Bhasa'],
                ['language_code' => 'el', 'language_name' => 'Greek'],
                ['language_code' => 'roa-rup', 'language_name' => 'Aromanian'],
                ['language_code' => 'la', 'language_name' => 'Latin'],
                ['language_code' => 'oc', 'language_name' => 'Occitan'],
                ['language_code' => 'tl', 'language_name' => 'Tagalog'],
                ['language_code' => 'ht', 'language_name' => 'Haitian'],
                ['language_code' => 'mk', 'language_name' => 'Macedonian'],
                ['language_code' => 'ka', 'language_name' => 'Georgian'],
                ['language_code' => 'sh', 'language_name' => 'Serbo-Croatian'],
                ['language_code' => 'te', 'language_name' => 'Telugu'],
                ['language_code' => 'pms', 'language_name' => 'Piedmontese'],
                ['language_code' => 'ceb', 'language_name' => 'Cebuano'],
                ['language_code' => 'ta', 'language_name' => 'Tamil'],
                ['language_code' => 'be-x-old', 'language_name' => 'Belarusian (Taraškievica]'],
                ['language_code' => 'br', 'language_name' => 'Breton'],
                ['language_code' => 'lv', 'language_name' => 'Latvian'],
                ['language_code' => 'jv', 'language_name' => 'Javanese'],
                ['language_code' => 'sq', 'language_name' => 'Albanian'],
                ['language_code' => 'be', 'language_name' => 'Belarusian'],
                ['language_code' => 'mr', 'language_name' => 'Marathi'],
                ['language_code' => 'cy', 'language_name' => 'Welsh'],
                ['language_code' => 'lb', 'language_name' => 'Luxembourgish'],
                ['language_code' => 'is', 'language_name' => 'Icelandic'],
                ['language_code' => 'bs', 'language_name' => 'Bosnian'],
                ['language_code' => 'yo', 'language_name' => 'Yoruba'],
                ['language_code' => 'mg', 'language_name' => 'Malagasy'],
                ['language_code' => 'an', 'language_name' => 'Aragonese'],
                ['language_code' => 'bpy', 'language_name' => 'Bishnupriya Manipuri'],
                ['language_code' => 'lmo', 'language_name' => 'Lombard'],
                ['language_code' => 'fy', 'language_name' => 'West Frisian'],
                ['language_code' => 'bn', 'language_name' => 'Bengali'],
                ['language_code' => 'io', 'language_name' => 'Ido'],
                ['language_code' => 'sw', 'language_name' => 'Swahili'],
                ['language_code' => 'gu', 'language_name' => 'Gujarati'],
                ['language_code' => 'ml', 'language_name' => 'Malayalam'],
                ['language_code' => 'pnb', 'language_name' => 'Western Panjabi'],
                ['language_code' => 'af', 'language_name' => 'Afrikaans'],
                ['language_code' => 'nds', 'language_name' => 'Low Saxon'],
                ['language_code' => 'scn', 'language_name' => 'Sicilian'],
                ['language_code' => 'ur', 'language_name' => 'Urdu'],
                ['language_code' => 'ku', 'language_name' => 'Kurdish'],
                ['language_code' => 'zh-yue', 'language_name' => 'Cantonese'],
                ['language_code' => 'hy', 'language_name' => 'Armenian'],
                ['language_code' => 'qu', 'language_name' => 'Quechua'],
                ['language_code' => 'su', 'language_name' => 'Sundanese'],
                ['language_code' => 'ne', 'language_name' => 'Nepali'],
                ['language_code' => 'diq', 'language_name' => 'Zazaki'],
                ['language_code' => 'ast', 'language_name' => 'Asturian'],
                ['language_code' => 'tt', 'language_name' => 'Tatar'],
                ['language_code' => 'nap', 'language_name' => 'Neapolitan'],
                ['language_code' => 'ga', 'language_name' => 'Irish'],
                ['language_code' => 'cv', 'language_name' => 'Chuvash'],
                ['language_code' => 'bat-smg', 'language_name' => 'Samogitian'],
                ['language_code' => 'wa', 'language_name' => 'Walloon'],
                ['language_code' => 'am', 'language_name' => 'Amharic'],
                ['language_code' => 'kn', 'language_name' => 'Kannada'],
                ['language_code' => 'als', 'language_name' => 'Alemannic'],
                ['language_code' => 'bug', 'language_name' => 'Buginese'],
                ['language_code' => 'my', 'language_name' => 'Burmese'],
                ['language_code' => 'ia', 'language_name' => 'Interlingua']
            ]
        );
    }
}
